name: Deploy Python-generated HTML to GitHub Pages

on:
  push:
    branches: ["main"]  # Trigger the workflow on push to the main branch
  workflow_dispatch:  # Allows manual triggering from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Ensure you have Python 3.x installed

      - name: Create public directory
        run: mkdir -p public  # Create the public directory if it doesn't exist

      - name: Run HTML generator
        run: |
          python html_generator.py  # Run your Python script
          ls -al public  # List the contents of the public directory for debugging

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public  # Specify the public directory as the artifact

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
